<?php

namespace Database\Seeders;

use App\Models\Garment;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GarmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Garment::insert([
            ["slug" => "camiseta", "name" => "Camiseta"],
            ["slug" => "blusa", "name" => "Blusa"],
            ["slug" => "camisa", "name" => "Camisa"],
            ["slug" => "polo", "name" => "Polo"],
            ["slug" => "top", "name" => "Top"],
            ["slug" => "sueter", "name" => "Suéter"],
            ["slug" => "jersey", "name" => "Jersey"],
            ["slug" => "cardigan", "name" => "Cardigan"],
            ["slug" => "chaleco", "name" => "Chaleco"],
            ["slug" => "chaqueta", "name" => "Chaqueta"],
            ["slug" => "abrigo", "name" => "Abrigo"],
            ["slug" => "parka", "name" => "Parka"],
            ["slug" => "anorak", "name" => "Anorak"],
            ["slug" => "chamarra", "name" => "Chamarra"],
            ["slug" => "cazadora", "name" => "Cazadora"],
            ["slug" => "chaqueta_cuero", "name" => "Chaqueta de cuero"],
            ["slug" => "chaqueta_vaquera", "name" => "Chaqueta vaquera"],
            ["slug" => "traje", "name" => "Traje"],
            ["slug" => "pantalon", "name" => "Pantalón"],
            ["slug" => "pantalones_cortos", "name" => "Pantalones cortos"],
            ["slug" => "pantalones_vaqueros", "name" => "Pantalones vaqueros"],
            ["slug" => "jeans", "name" => "Jeans"],
            ["slug" => "pantalon_vestir", "name" => "Pantalón de vestir"],
            ["slug" => "pantalon_deportivo", "name" => "Pantalón deportivo"],
            ["slug" => "falda", "name" => "Falda"],
            ["slug" => "minifalda", "name" => "Minifalda"],
            ["slug" => "falda_larga", "name" => "Falda larga"],
            ["slug" => "falda_lapiz", "name" => "Falda lápiz"],
            ["slug" => "vestido", "name" => "Vestido"],
            ["slug" => "vestido_coctel", "name" => "Vestido de cóctel"],
            ["slug" => "vestido_noche", "name" => "Vestido de noche"],
            ["slug" => "vestido_largo", "name" => "Vestido largo"],
            ["slug" => "vestido_corto", "name" => "Vestido corto"],
            ["slug" => "traje_bano", "name" => "Traje de baño"],
            ["slug" => "bikini", "name" => "Bikini"],
            ["slug" => "banador", "name" => "Bañador"],
            ["slug" => "ropa_interior", "name" => "Ropa interior"],
            ["slug" => "sujetador", "name" => "Sujetador"],
            ["slug" => "calzoncillos", "name" => "Calzoncillos"],
            ["slug" => "bragas", "name" => "Bragas"],
            ["slug" => "medias", "name" => "Medias"],
            ["slug" => "calcetines", "name" => "Calcetines"],
            ["slug" => "calcetines_largos", "name" => "Calcetines largos"],
            ["slug" => "calcetines_cortos", "name" => "Calcetines cortos"],
            ["slug" => "calcetines_tobilleros", "name" => "Calcetines tobilleros"],
            ["slug" => "calcetines_deportivos", "name" => "Calcetines deportivos"],
            ["slug" => "calcetines_vestir", "name" => "Calcetines de vestir"],
            ["slug" => "medias_panty", "name" => "Medias panty"],
            ["slug" => "medias_compresion", "name" => "Medias de compresión"],
            ["slug" => "calcetines_invisibles", "name" => "Calcetines invisibles"],
            ["slug" => "ropa_deportiva", "name" => "Ropa deportiva"],
            ["slug" => "camiseta_deportiva", "name" => "Camiseta deportiva"],
            ["slug" => "pantalon_deportivo", "name" => "Pantalón deportivo"],
            ["slug" => "chandal", "name" => "Chándal"],
            ["slug" => "sudadera", "name" => "Sudadera"],
            ["slug" => "mallas", "name" => "Mallas"],
            ["slug" => "leggings", "name" => "Leggings"],
            ["slug" => "chaqueta_deportiva", "name" => "Chaqueta deportiva"],
            ["slug" => "ropa_dormir", "name" => "Ropa de dormir"],
            ["slug" => "pijama", "name" => "Pijama"],
            ["slug" => "camison", "name" => "Camisón"],
            ["slug" => "bata", "name" => "Bata"],
            ["slug" => "zapatillas_casa", "name" => "Zapatillas de estar por casa"],
            ["slug" => "zapatillas_deporte", "name" => "Zapatillas de deporte"],
            ["slug" => "zapatos", "name" => "Zapatos"],
            ["slug" => "zapatos_vestir", "name" => "Zapatos de vestir"],
            ["slug" => "zapatos_tacon", "name" => "Zapatos de tacón"],
            ["slug" => "botas", "name" => "Botas"],
            ["slug" => "botines", "name" => "Botines"],
            ["slug" => "sandalias", "name" => "Sandalias"],
            ["slug" => "alpargatas", "name" => "Alpargatas"],
            ["slug" => "mocasines", "name" => "Mocasines"],
            ["slug" => "bailarinas", "name" => "Bailarinas"],
            ["slug" => "oxfords", "name" => "Oxfords"],
            ["slug" => "chanclas", "name" => "Chanclas"],
            ["slug" => "zapatos_plataforma", "name" => "Zapatos de plataforma"],
            ["slug" => "zapatos_planos", "name" => "Zapatos planos"],
            ["slug" => "accesorios_cabeza", "name" => "Accesorios para la cabeza"],
            ["slug" => "gorra", "name" => "Gorra"],
            ["slug" => "sombrero", "name" => "Sombrero"],
            ["slug" => "boina", "name" => "Boina"],
            ["slug" => "diadema", "name" => "Diadema"],
            ["slug" => "panuelo", "name" => "Pañuelo"],
            ["slug" => "bufanda", "name" => "Bufanda"],
            ["slug" => "gorro_lana", "name" => "Gorro de lana"],
            ["slug" => "gorro_punto", "name" => "Gorro de punto"],
            ["slug" => "gorro_bano", "name" => "Gorro de baño"],
            ["slug" => "sombrero_paja", "name" => "Sombrero de paja"],
            ["slug" => "accesorios_cuello", "name" => "Accesorios para el cuello"],
            ["slug" => "collar", "name" => "Collar"],
            ["slug" => "bufanda_2", "name" => "Bufanda"],
            ["slug" => "pashmina", "name" => "Pashmina"],
            ["slug" => "panuelo_2", "name" => "Pañuelo"],
            ["slug" => "fular", "name" => "Fular"],
            ["slug" => "accesorios_mano", "name" => "Accesorios para las manos"],
            ["slug" => "guantes", "name" => "Guantes"],
            ["slug" => "mitones", "name" => "Mitones"],
            ["slug" => "manoplas", "name" => "Manoplas"],
            ["slug" => "pulsera", "name" => "Pulsera"],
            ["slug" => "anillo", "name" => "Anillo"]
        ]);
    }
}
